# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql
  user: root
  database: photocracy_development

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3

staging:
  <<: *default


cucumber:
  <<: *TEST
